-- ========================================
-- Ejercicio 3.1.1.
-- ========================================
-- ========================================
-- CREACIÓN DE TABLAS DE CAPACITACIÓN
-- ========================================

CREATE TABLE capacitacion (
  capacitacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  horas NUMBER(5,2) NOT NULL,
  descripcion VARCHAR2(200)
);

CREATE TABLE empleado_capacitacion (
  employee_id NUMBER NOT NULL,
  capacitacion_id NUMBER NOT NULL,
  CONSTRAINT fk_emp_cap_emp FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
  CONSTRAINT fk_emp_cap_cap FOREIGN KEY (capacitacion_id) REFERENCES capacitacion(capacitacion_id)
);

-- ========================================
-- INSERCIÓN DE DATOS DE PRUEBA
-- ========================================

-- Capacitaciones
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Gestión de Proyectos', 12, 'Taller sobre planificación y gestión ágil.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Seguridad Informática', 8, 'Buenas prácticas en ciberseguridad.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Liderazgo', 10, 'Formación en habilidades de liderazgo.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Comunicación Efectiva', 6, 'Mejora de habilidades comunicativas.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Bases de Datos Avanzadas', 14, 'Optimización y diseño de bases de datos.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Desarrollo Web', 16, 'HTML, CSS, JavaScript y frameworks modernos.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Machine Learning', 20, 'Fundamentos del aprendizaje automático.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Excel Avanzado', 8, 'Análisis de datos con Excel.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Atención al Cliente', 5, 'Mejora de la experiencia del cliente.');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Trabajo en Equipo', 7, 'Dinámicas y metodologías colaborativas.');

-- Empleado-Capacitación (asignaciones)
INSERT INTO empleado_capacitacion VALUES (1, 1);
INSERT INTO empleado_capacitacion VALUES (1, 3);
INSERT INTO empleado_capacitacion VALUES (1, 5);
INSERT INTO empleado_capacitacion VALUES (2, 2);
INSERT INTO empleado_capacitacion VALUES (2, 6);
INSERT INTO empleado_capacitacion VALUES (3, 4);
INSERT INTO empleado_capacitacion VALUES (3, 7);
INSERT INTO empleado_capacitacion VALUES (4, 8);
INSERT INTO empleado_capacitacion VALUES (4, 9);
INSERT INTO empleado_capacitacion VALUES (4, 10);

COMMIT;

CREATE OR REPLACE PACKAGE capacitacion_pkg AS
  FUNCTION horas_capacitacion_total(p_employee_id NUMBER) RETURN NUMBER;
END capacitacion_pkg;
/

CREATE OR REPLACE PACKAGE BODY capacitacion_pkg AS

  FUNCTION horas_capacitacion_total(p_employee_id NUMBER) RETURN NUMBER IS
    v_total_horas NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(c.horas), 0)
    INTO v_total_horas
    FROM capacitacion c
    JOIN empleado_capacitacion ec ON c.capacitacion_id = ec.capacitacion_id
    WHERE ec.employee_id = p_employee_id;

    DBMS_OUTPUT.PUT_LINE('Empleado ID: ' || p_employee_id || ' | Total horas de capacitación: ' || v_total_horas);

    RETURN v_total_horas;
  END;

END capacitacion_pkg;
/

SET SERVEROUTPUT ON;

VAR v_horas_cap NUMBER;
EXEC :v_horas_cap := capacitacion_pkg.horas_capacitacion_total(1);
PRINT v_horas_cap;